apiVersion: v1
kind: Service
metadata:
  name: postandcomment
  labels:
    app: postandcomment
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: postandcomment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000